name: instagram_mass_unliker
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  puppeteer: ^3.20.0
  path: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
